## Pandas and Numpy functions

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("Emp.csv")

In [4]:
df

empno       ename         job        DOJ        DOB  deptid   salary
0       1        Anil       Clerk        NaN        NaN     NaN      NaN
1       2  Balkrushna         NaN  15-Jul-17  16-Mar-12    10.0  10000.0
2       3      Mathew     Manager  16-Mar-12  16-Mar-92    20.0  50000.0
3       4       Suhas     Manager  16-Mar-12  17-Mar-91    20.0      NaN
4       5       Vimal  Accountant  18-Mar-17  18-Mar-91    20.0  45000.0
5       6       Kamal  Accountant  19-Nov-13  18-Mar-91    20.0  45000.0
6       7       Nanda     Manager  20-Mar-12  20-Jan-97    20.0  52000.0
7       8      Khushi     Manager  21-Mar-12  21-Jun-94    20.0  56000.0
8       9       Sayee      Cleark  16-Mar-12  22-Aug-98     NaN  21000.0
9      10       Sakhi  Accountant  23-Mar-12  14-Mar-91    30.0  46000.0
10     11      Soniya  Accountant  24-Mar-14  24-Mar-91    30.0  47000.0

In [5]:
df.head(3)

empno       ename      job        DOJ        DOB  deptid   salary
0      1        Anil    Clerk        NaN        NaN     NaN      NaN
1      2  Balkrushna      NaN  15-Jul-17  16-Mar-12    10.0  10000.0
2      3      Mathew  Manager  16-Mar-12  16-Mar-92    20.0  50000.0

In [11]:
df.dtypes

empno       int64
ename      object
job        object
DOJ        object
DOB        object
deptid    float64
salary    float64
dtype: object

In [15]:
df['salary'].dtypes  # shows datatype of 'salary' columns

dtype('float64')

In [16]:
df.columns  # shows columns

Index(['empno', 'ename', 'job', 'DOJ', 'DOB', 'deptid', 'salary'], dtype='object')

In [18]:
df.describe()  # shows basic statics

empno     deptid        salary
count  11.000000   9.000000      9.000000
mean    6.000000  21.111111  41333.333333
std     3.316625   6.009252  15329.709717
min     1.000000  10.000000  10000.000000
25%     3.500000  20.000000  45000.000000
50%     6.000000  20.000000  46000.000000
75%     8.500000  20.000000  50000.000000
max    11.000000  30.000000  56000.000000

In [19]:
df['salary'].max()

56000.0

In [21]:
df['salary'].min()

10000.0

In [25]:
df.dropna()

empno   ename         job        DOJ        DOB  deptid   salary
2       3  Mathew     Manager  16-Mar-12  16-Mar-92    20.0  50000.0
4       5   Vimal  Accountant  18-Mar-17  18-Mar-91    20.0  45000.0
5       6   Kamal  Accountant  19-Nov-13  18-Mar-91    20.0  45000.0
6       7   Nanda     Manager  20-Mar-12  20-Jan-97    20.0  52000.0
7       8  Khushi     Manager  21-Mar-12  21-Jun-94    20.0  56000.0
9      10   Sakhi  Accountant  23-Mar-12  14-Mar-91    30.0  46000.0
10     11  Soniya  Accountant  24-Mar-14  24-Mar-91    30.0  47000.0

In [24]:
df

empno       ename         job        DOJ        DOB  deptid   salary
0       1        Anil       Clerk        NaN        NaN     NaN      NaN
1       2  Balkrushna         NaN  15-Jul-17  16-Mar-12    10.0  10000.0
2       3      Mathew     Manager  16-Mar-12  16-Mar-92    20.0  50000.0
3       4       Suhas     Manager  16-Mar-12  17-Mar-91    20.0      NaN
4       5       Vimal  Accountant  18-Mar-17  18-Mar-91    20.0  45000.0
5       6       Kamal  Accountant  19-Nov-13  18-Mar-91    20.0  45000.0
6       7       Nanda     Manager  20-Mar-12  20-Jan-97    20.0  52000.0
7       8      Khushi     Manager  21-Mar-12  21-Jun-94    20.0  56000.0
8       9       Sayee      Cleark  16-Mar-12  22-Aug-98     NaN  21000.0
9      10       Sakhi  Accountant  23-Mar-12  14-Mar-91    30.0  46000.0
10     11      Soniya  Accountant  24-Mar-14  24-Mar-91    30.0  47000.0

In [27]:
df.head(5).mean()

empno         3.0
deptid       17.5
salary    35000.0
dtype: float64

In [29]:
df[:5].mean()

empno         3.0
deptid       17.5
salary    35000.0
dtype: float64

In [30]:
# df['name'] - Subset the data frame using column name
# df.name - Use the column name as an attribute

In [34]:
type(df['salary'])

pandas.core.series.Series

In [33]:
type(df.salary)

pandas.core.series.Series

In [37]:
df['salary'].count()  # Count of 'Salary'

9

In [38]:
df['salary'].mean()  # Average Salary

41333.333333333336

In [40]:
df['salary'].describe()  # Basic stats of salary column

count        9.000000
mean     41333.333333
std      15329.709717
min      10000.000000
25%      45000.000000
50%      46000.000000
75%      50000.000000
max      56000.000000
Name: salary, dtype: float64

In [45]:
# Group data using rank
df_rank = df.groupby(['job'])

In [46]:
# Calculate mean value for each numeric column per each group
df_rank.mean()

empno  deptid        salary
job                                    
Accountant    8.0    25.0  45750.000000
Cleark        9.0     NaN  21000.000000
Clerk         1.0     NaN           NaN
Manager       5.5    20.0  52666.666667

In [49]:
# Calculate mean salary for each job
df.groupby('job')[['salary']].mean()

salary
job                     
Accountant  45750.000000
Cleark      21000.000000
Clerk                NaN
Manager     52666.666667

In [67]:
# Calculate mean salary for each job rank
df_sub = df[ df['salary'] < 30000]

In [68]:
df_sub

empno       ename     job        DOJ        DOB  deptid   salary
1      2  Balkrushna     NaN  15-Jul-17  16-Mar-12    10.0  10000.0
8      9       Sayee  Cleark  16-Mar-12  22-Aug-98     NaN  21000.0

In [84]:
df_subset = df[(df['salary'] > 30000 | (df['job'] == 'Cleark'))]

In [85]:
df_subset.ename

1     Balkrushna
2         Mathew
4          Vimal
5          Kamal
6          Nanda
7         Khushi
8          Sayee
9          Sakhi
10        Soniya
Name: ename, dtype: object

In [90]:
df_subset['ename']

1     Balkrushna
2         Mathew
4          Vimal
5          Kamal
6          Nanda
7         Khushi
8          Sayee
9          Sakhi
10        Soniya
Name: ename, dtype: object

In [79]:
df_subset = df.groupby(['job'], sort = False)[['salary']].mean()
df_subset

salary
job                     
Clerk                NaN
Manager     52666.666667
Accountant  45750.000000
Cleark      21000.000000

In [72]:
# Select only those rows that contain female professors
# df_f = df[df['sex'] == 'False'] 

In [92]:
# Select rows by their labels
# df_sub.loc[10: 20, ['rank', 'sex', 'salary']]  # Extracted using labels of the rows
# df_sub.iloc[10:20, [0, 3, 4, 5]]  # Extracted using locations

In [93]:
df.columns

Index(['empno', 'ename', 'job', 'DOJ', 'DOB', 'deptid', 'salary'], dtype='object')

In [95]:
# Select rows by their labels
df.loc[:5, ['empno', 'ename']]

empno       ename
0      1        Anil
1      2  Balkrushna
2      3      Mathew
3      4       Suhas
4      5       Vimal
5      6       Kamal

In [98]:
# df.iloc[-1] # last row
# df.iloc[i]  # (i+1)the row
# df.iloc[0]  # First columns
# df.iloc[:, -1]  # last column
# df.iloc[:, 0:2]  # First 2 columns
# df.iloc[1: 3, 0: 2]  # Second through third rows and first 2 columns
# df.iloc[[0, 5], [1, 3]]  # 1st and 6th rows and 2nd and 4th columns

ename        DOJ
0   Anil        NaN
5  Kamal  19-Nov-13

## Missing Value

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("Emp.csv")

In [4]:
df

empno       ename         job        DOJ        DOB  deptid   salary
0       1        Anil       Clerk        NaN        NaN     NaN      NaN
1       2  Balkrushna         NaN  15-Jul-17  16-Mar-12    10.0  10000.0
2       3      Mathew     Manager  16-Mar-12  16-Mar-92    20.0  50000.0
3       4       Suhas     Manager  16-Mar-12  17-Mar-91    20.0      NaN
4       5       Vimal  Accountant  18-Mar-17  18-Mar-91    20.0  45000.0
5       6       Kamal  Accountant  19-Nov-13  18-Mar-91    20.0  45000.0
6       7       Nanda     Manager  20-Mar-12  20-Jan-97    20.0  52000.0
7       8      Khushi     Manager  21-Mar-12  21-Jun-94    20.0  56000.0
8       9       Sayee      Cleark  16-Mar-12  22-Aug-98     NaN  21000.0
9      10       Sakhi  Accountant  23-Mar-12  14-Mar-91    30.0  46000.0
10     11      Soniya  Accountant  24-Mar-14  24-Mar-91    30.0  47000.0

In [5]:
df.head(3)

empno       ename      job        DOJ        DOB  deptid   salary
0      1        Anil    Clerk        NaN        NaN     NaN      NaN
1      2  Balkrushna      NaN  15-Jul-17  16-Mar-12    10.0  10000.0
2      3      Mathew  Manager  16-Mar-12  16-Mar-92    20.0  50000.0

In [11]:
df.dtypes

empno       int64
ename      object
job        object
DOJ        object
DOB        object
deptid    float64
salary    float64
dtype: object

In [15]:
df['salary'].dtypes  # shows datatype of 'salary' columns

dtype('float64')

In [16]:
df.columns  # shows columns

Index(['empno', 'ename', 'job', 'DOJ', 'DOB', 'deptid', 'salary'], dtype='object')

In [18]:
df.describe()  # shows basic statics

empno     deptid        salary
count  11.000000   9.000000      9.000000
mean    6.000000  21.111111  41333.333333
std     3.316625   6.009252  15329.709717
min     1.000000  10.000000  10000.000000
25%     3.500000  20.000000  45000.000000
50%     6.000000  20.000000  46000.000000
75%     8.500000  20.000000  50000.000000
max    11.000000  30.000000  56000.000000

In [19]:
df['salary'].max()

56000.0

In [21]:
df['salary'].min()

10000.0

In [25]:
df.dropna()

empno   ename         job        DOJ        DOB  deptid   salary
2       3  Mathew     Manager  16-Mar-12  16-Mar-92    20.0  50000.0
4       5   Vimal  Accountant  18-Mar-17  18-Mar-91    20.0  45000.0
5       6   Kamal  Accountant  19-Nov-13  18-Mar-91    20.0  45000.0
6       7   Nanda     Manager  20-Mar-12  20-Jan-97    20.0  52000.0
7       8  Khushi     Manager  21-Mar-12  21-Jun-94    20.0  56000.0
9      10   Sakhi  Accountant  23-Mar-12  14-Mar-91    30.0  46000.0
10     11  Soniya  Accountant  24-Mar-14  24-Mar-91    30.0  47000.0

In [24]:
df

empno       ename         job        DOJ        DOB  deptid   salary
0       1        Anil       Clerk        NaN        NaN     NaN      NaN
1       2  Balkrushna         NaN  15-Jul-17  16-Mar-12    10.0  10000.0
2       3      Mathew     Manager  16-Mar-12  16-Mar-92    20.0  50000.0
3       4       Suhas     Manager  16-Mar-12  17-Mar-91    20.0      NaN
4       5       Vimal  Accountant  18-Mar-17  18-Mar-91    20.0  45000.0
5       6       Kamal  Accountant  19-Nov-13  18-Mar-91    20.0  45000.0
6       7       Nanda     Manager  20-Mar-12  20-Jan-97    20.0  52000.0
7       8      Khushi     Manager  21-Mar-12  21-Jun-94    20.0  56000.0
8       9       Sayee      Cleark  16-Mar-12  22-Aug-98     NaN  21000.0
9      10       Sakhi  Accountant  23-Mar-12  14-Mar-91    30.0  46000.0
10     11      Soniya  Accountant  24-Mar-14  24-Mar-91    30.0  47000.0

In [27]:
df.head(5).mean()

empno         3.0
deptid       17.5
salary    35000.0
dtype: float64

In [29]:
df[:5].mean()

empno         3.0
deptid       17.5
salary    35000.0
dtype: float64

In [30]:
# df['name'] - Subset the data frame using column name
# df.name - Use the column name as an attribute

In [34]:
type(df['salary'])

pandas.core.series.Series

In [33]:
type(df.salary)

pandas.core.series.Series

In [37]:
df['salary'].count()  # Count of 'Salary'

9

In [38]:
df['salary'].mean()  # Average Salary

41333.333333333336

In [40]:
df['salary'].describe()  # Basic stats of salary column

count        9.000000
mean     41333.333333
std      15329.709717
min      10000.000000
25%      45000.000000
50%      46000.000000
75%      50000.000000
max      56000.000000
Name: salary, dtype: float64

In [45]:
# Group data using rank
df_rank = df.groupby(['job'])

In [46]:
# Calculate mean value for each numeric column per each group
df_rank.mean()

empno  deptid        salary
job                                    
Accountant    8.0    25.0  45750.000000
Cleark        9.0     NaN  21000.000000
Clerk         1.0     NaN           NaN
Manager       5.5    20.0  52666.666667

In [49]:
# Calculate mean salary for each job
df.groupby('job')[['salary']].mean()

salary
job                     
Accountant  45750.000000
Cleark      21000.000000
Clerk                NaN
Manager     52666.666667

In [67]:
# Calculate mean salary for each job rank
df_sub = df[ df['salary'] < 30000]

In [68]:
df_sub

empno       ename     job        DOJ        DOB  deptid   salary
1      2  Balkrushna     NaN  15-Jul-17  16-Mar-12    10.0  10000.0
8      9       Sayee  Cleark  16-Mar-12  22-Aug-98     NaN  21000.0

In [84]:
df_subset = df[(df['salary'] > 30000 | (df['job'] == 'Cleark'))]

In [85]:
df_subset.ename

1     Balkrushna
2         Mathew
4          Vimal
5          Kamal
6          Nanda
7         Khushi
8          Sayee
9          Sakhi
10        Soniya
Name: ename, dtype: object

In [90]:
df_subset['ename']

1     Balkrushna
2         Mathew
4          Vimal
5          Kamal
6          Nanda
7         Khushi
8          Sayee
9          Sakhi
10        Soniya
Name: ename, dtype: object

In [79]:
df_subset = df.groupby(['job'], sort = False)[['salary']].mean()
df_subset

salary
job                     
Clerk                NaN
Manager     52666.666667
Accountant  45750.000000
Cleark      21000.000000

In [72]:
# Select only those rows that contain female professors
# df_f = df[df['sex'] == 'False'] 

In [92]:
# Select rows by their labels
# df_sub.loc[10: 20, ['rank', 'sex', 'salary']]  # Extracted using labels of the rows
# df_sub.iloc[10:20, [0, 3, 4, 5]]  # Extracted using locations

In [93]:
df.columns

Index(['empno', 'ename', 'job', 'DOJ', 'DOB', 'deptid', 'salary'], dtype='object')

In [95]:
# Select rows by their labels
df.loc[:5, ['empno', 'ename']]

empno       ename
0      1        Anil
1      2  Balkrushna
2      3      Mathew
3      4       Suhas
4      5       Vimal
5      6       Kamal

In [98]:
# df.iloc[-1] # last row
# df.iloc[i]  # (i+1)the row
# df.iloc[0]  # First columns
# df.iloc[:, -1]  # last column
# df.iloc[:, 0:2]  # First 2 columns
# df.iloc[1: 3, 0: 2]  # Second through third rows and first 2 columns
# df.iloc[[0, 5], [1, 3]]  # 1st and 6th rows and 2nd and 4th columns

ename        DOJ
0   Anil        NaN
5  Kamal  19-Nov-13

## Missing Values

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Emp.csv')

In [3]:
df.head()

empno       ename         job        DOJ        DOB  deptid   salary
0      1        Anil       Clerk        NaN        NaN     NaN      NaN
1      2  Balkrushna         NaN  15-Jul-17  16-Mar-12    10.0  10000.0
2      3      Mathew     Manager  16-Mar-12  16-Mar-92    20.0  50000.0
3      4       Suhas     Manager  16-Mar-12  17-Mar-91    20.0      NaN
4      5       Vimal  Accountant  18-Mar-17  18-Mar-91    20.0  45000.0

In [4]:
df.isna()  # To check whether there is empty values or not

empno  ename    job    DOJ    DOB  deptid  salary
0   False  False  False   True   True    True    True
1   False  False   True  False  False   False   False
2   False  False  False  False  False   False   False
3   False  False  False  False  False   False    True
4   False  False  False  False  False   False   False
5   False  False  False  False  False   False   False
6   False  False  False  False  False   False   False
7   False  False  False  False  False   False   False
8   False  False  False  False  False    True   False
9   False  False  False  False  False   False   False
10  False  False  False  False  False   False   False

In [5]:
df.dropna(thresh = 6)

empno       ename         job        DOJ        DOB  deptid   salary
1       2  Balkrushna         NaN  15-Jul-17  16-Mar-12    10.0  10000.0
2       3      Mathew     Manager  16-Mar-12  16-Mar-92    20.0  50000.0
3       4       Suhas     Manager  16-Mar-12  17-Mar-91    20.0      NaN
4       5       Vimal  Accountant  18-Mar-17  18-Mar-91    20.0  45000.0
5       6       Kamal  Accountant  19-Nov-13  18-Mar-91    20.0  45000.0
6       7       Nanda     Manager  20-Mar-12  20-Jan-97    20.0  52000.0
7       8      Khushi     Manager  21-Mar-12  21-Jun-94    20.0  56000.0
8       9       Sayee      Cleark  16-Mar-12  22-Aug-98     NaN  21000.0
9      10       Sakhi  Accountant  23-Mar-12  14-Mar-91    30.0  46000.0
10     11      Soniya  Accountant  24-Mar-14  24-Mar-91    30.0  47000.0

In [6]:
df.fillna(0)  # Filling the nan with 0

empno       ename         job        DOJ        DOB  deptid   salary
0       1        Anil       Clerk          0          0     0.0      0.0
1       2  Balkrushna           0  15-Jul-17  16-Mar-12    10.0  10000.0
2       3      Mathew     Manager  16-Mar-12  16-Mar-92    20.0  50000.0
3       4       Suhas     Manager  16-Mar-12  17-Mar-91    20.0      0.0
4       5       Vimal  Accountant  18-Mar-17  18-Mar-91    20.0  45000.0
5       6       Kamal  Accountant  19-Nov-13  18-Mar-91    20.0  45000.0
6       7       Nanda     Manager  20-Mar-12  20-Jan-97    20.0  52000.0
7       8      Khushi     Manager  21-Mar-12  21-Jun-94    20.0  56000.0
8       9       Sayee      Cleark  16-Mar-12  22-Aug-98     0.0  21000.0
9      10       Sakhi  Accountant  23-Mar-12  14-Mar-91    30.0  46000.0
10     11      Soniya  Accountant  24-Mar-14  24-Mar-91    30.0  47000.0

In [7]:
df.isna()

empno  ename    job    DOJ    DOB  deptid  salary
0   False  False  False   True   True    True    True
1   False  False   True  False  False   False   False
2   False  False  False  False  False   False   False
3   False  False  False  False  False   False    True
4   False  False  False  False  False   False   False
5   False  False  False  False  False   False   False
6   False  False  False  False  False   False   False
7   False  False  False  False  False   False   False
8   False  False  False  False  False    True   False
9   False  False  False  False  False   False   False
10  False  False  False  False  False   False   False

In [8]:
df['deptid'].fillna(0)  # apply fillna to specific column

0      0.0
1     10.0
2     20.0
3     20.0
4     20.0
5     20.0
6     20.0
7     20.0
8      0.0
9     30.0
10    30.0
Name: deptid, dtype: float64

In [9]:
df

empno       ename         job        DOJ        DOB  deptid   salary
0       1        Anil       Clerk        NaN        NaN     NaN      NaN
1       2  Balkrushna         NaN  15-Jul-17  16-Mar-12    10.0  10000.0
2       3      Mathew     Manager  16-Mar-12  16-Mar-92    20.0  50000.0
3       4       Suhas     Manager  16-Mar-12  17-Mar-91    20.0      NaN
4       5       Vimal  Accountant  18-Mar-17  18-Mar-91    20.0  45000.0
5       6       Kamal  Accountant  19-Nov-13  18-Mar-91    20.0  45000.0
6       7       Nanda     Manager  20-Mar-12  20-Jan-97    20.0  52000.0
7       8      Khushi     Manager  21-Mar-12  21-Jun-94    20.0  56000.0
8       9       Sayee      Cleark  16-Mar-12  22-Aug-98     NaN  21000.0
9      10       Sakhi  Accountant  23-Mar-12  14-Mar-91    30.0  46000.0
10     11      Soniya  Accountant  24-Mar-14  24-Mar-91    30.0  47000.0

In [10]:
df['salary'].ffill() # Fill it with the next missing value
# Forward Fill and Backward Fill

0         NaN
1     10000.0
2     50000.0
3     50000.0
4     45000.0
5     45000.0
6     52000.0
7     56000.0
8     21000.0
9     46000.0
10    47000.0
Name: salary, dtype: float64

In [11]:
# Backward fill
df['deptid'].bfill()  # fill it with value that came before the empty value

0     10.0
1     10.0
2     20.0
3     20.0
4     20.0
5     20.0
6     20.0
7     20.0
8     30.0
9     30.0
10    30.0
Name: deptid, dtype: float64

In [12]:
# Drops the duplicated values from the dataset
df.drop_duplicates() 

empno       ename         job        DOJ        DOB  deptid   salary
0       1        Anil       Clerk        NaN        NaN     NaN      NaN
1       2  Balkrushna         NaN  15-Jul-17  16-Mar-12    10.0  10000.0
2       3      Mathew     Manager  16-Mar-12  16-Mar-92    20.0  50000.0
3       4       Suhas     Manager  16-Mar-12  17-Mar-91    20.0      NaN
4       5       Vimal  Accountant  18-Mar-17  18-Mar-91    20.0  45000.0
5       6       Kamal  Accountant  19-Nov-13  18-Mar-91    20.0  45000.0
6       7       Nanda     Manager  20-Mar-12  20-Jan-97    20.0  52000.0
7       8      Khushi     Manager  21-Mar-12  21-Jun-94    20.0  56000.0
8       9       Sayee      Cleark  16-Mar-12  22-Aug-98     NaN  21000.0
9      10       Sakhi  Accountant  23-Mar-12  14-Mar-91    30.0  46000.0
10     11      Soniya  Accountant  24-Mar-14  24-Mar-91    30.0  47000.0

## Imputer Class in sklearn

In [13]:
import numpy as np
# Importing the SimpleImputer class
from sklearn.impute import SimpleImputer

# Imputer object using the mean strategy and 
# missing_values type for imputation

imputer = SimpleImputer(missing_values = np.nan,
                       strategy = 'mean')
data = [[12, np.nan, 34], [10, 32, np.nan], [np.nan, 11, 20]]

print("Original Data : \n", data)
# Fitting the data to the imputer object
imputer = imputer.fit(data)
# Imputing the data
data = imputer.transform(data)
print("Imputed Data: \n", data)

# object --> fit --> transform

Original Data : 
 [[12, nan, 34], [10, 32, nan], [nan, 11, 20]]
Imputed Data: 
 [[12.  21.5 34. ]
 [10.  32.  27. ]
 [11.  11.  20. ]]


In [14]:
df

empno       ename         job        DOJ        DOB  deptid   salary
0       1        Anil       Clerk        NaN        NaN     NaN      NaN
1       2  Balkrushna         NaN  15-Jul-17  16-Mar-12    10.0  10000.0
2       3      Mathew     Manager  16-Mar-12  16-Mar-92    20.0  50000.0
3       4       Suhas     Manager  16-Mar-12  17-Mar-91    20.0      NaN
4       5       Vimal  Accountant  18-Mar-17  18-Mar-91    20.0  45000.0
5       6       Kamal  Accountant  19-Nov-13  18-Mar-91    20.0  45000.0
6       7       Nanda     Manager  20-Mar-12  20-Jan-97    20.0  52000.0
7       8      Khushi     Manager  21-Mar-12  21-Jun-94    20.0  56000.0
8       9       Sayee      Cleark  16-Mar-12  22-Aug-98     NaN  21000.0
9      10       Sakhi  Accountant  23-Mar-12  14-Mar-91    30.0  46000.0
10     11      Soniya  Accountant  24-Mar-14  24-Mar-91    30.0  47000.0

## Pima-Diabetes Dataset

In [15]:
dataset = pd.read_csv('pima-indians-diabetes.csv', header = None)
dataset.head(20)

0    1   2   3    4     5      6   7  8
0    6  148  72  35    0  33.6  0.627  50  1
1    1   85  66  29    0  26.6  0.351  31  0
2    8  183  64   0    0  23.3  0.672  32  1
3    1   89  66  23   94  28.1  0.167  21  0
4    0  137  40  35  168  43.1  2.288  33  1
5    5  116  74   0    0  25.6  0.201  30  0
6    3   78  50  32   88  31.0  0.248  26  1
7   10  115   0   0    0  35.3  0.134  29  0
8    2  197  70  45  543  30.5  0.158  53  1
9    8  125  96   0    0   0.0  0.232  54  1
10   4  110  92   0    0  37.6  0.191  30  0
11  10  168  74   0    0  38.0  0.537  34  1
12  10  139  80   0    0  27.1  1.441  57  0
13   1  189  60  23  846  30.1  0.398  59  1
14   5  166  72  19  175  25.8  0.587  51  1
15   7  100   0   0    0  30.0  0.484  32  1
16   0  118  84  47  230  45.8  0.551  31  1
17   7  107  74   0    0  29.6  0.254  31  1
18   1  103  30  38   83  43.3  0.183  33  0
19   1  115  70  30   96  34.6  0.529  32  1

In [68]:
dataset[[1, 2, 3, 4, 5]] = dataset[[1, 2, 3, 4, 5]].replace(0, np.nan)

In [69]:
print(dataset.shape)
# replace '0' values with 'nan'
dataset[[1, 2, 3, 4, 5]] = dataset[[1, 2, 3, 4, 5]].replace(0, np.nan)
# drop rows with missing values
dataset.dropna(inplace=True)
# summarize the shape of the data with missing rows removed
print(dataset.shape)

(392, 9)
(392, 9)


In [70]:
dataset[[1, 2, 3, 4, 5]] = dataset[[1, 2, 3, 4, 5]].replace(0, np.nan)
# fill missing values with mean column values
dataset.fillna(dataset.mean(), inplace=True)
# count the number of NaN values in each column
print(dataset.isnull().sum())

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64


In [72]:
dataset[[1, 2, 3, 4, 5]] = dataset[[1, 2, 3, 4, 5]].replace(0, np.nan)
# Retrieve the numpy array
values = dataset.values
# Define the imputer 
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
# Transform the dataset
transformed_values = imputer.fit_transform(values)
# count the number of Nan values in each column

## Normalization (l1, l2)

In [22]:
import numpy as np
#demo of Normalizer
from sklearn.preprocessing import Normalizer
#data = np.array([[1.0, 2.0], [2.0, 3.0]])

data = np.array([[4.0, 8.0], [6.0, 5.0]])

n_max = Normalizer(norm='max')
print(n_max.fit_transform(data))

d1 = n_max.fit_transform(data)

print(data)

# print(d1)

[[0.5        1.        ]
 [1.         0.83333333]]
[[4. 8.]
 [6. 5.]]


In [23]:
n_l1 = Normalizer(norm='l1')
n_l2 = Normalizer(norm='l2')

print(n_l1.fit_transform(data))
print(n_l2.fit_transform(data))

[[0.33333333 0.66666667]
 [0.54545455 0.45454545]]
[[0.4472136  0.89442719]
 [0.76822128 0.6401844 ]]


In [24]:
# Removing the columns which do not provide sufficient output
# Whether the values in the column are suitable or not
from sklearn.feature_selection import VarianceThreshold
import numpy as np
X = np.array([[-3.5077778, -3.45267063, 0.9681903], 
             [-3.82581314, 5.77984646, 1.78926338], 
             [-2.62090281, -4.90597966, 0.277943565]])

vt = VarianceThreshold(threshold=1.5)
x_t = vt.fit_transform(X)

x_t   # VarianceThreshold

array([[-3.45267063],
       [ 5.77984646],
       [-4.90597966]])

In [25]:
X = np.array([[0, 2, 0, 3], [0, 1, 4, 3], [0, 1, 1, 3]])

vt = VarianceThreshold(threshold=1.5)
x_t = vt.fit_transform(X)

print(x_t)

[[0]
 [4]
 [1]]


## Iris Datset (Variance Threshold)

In [26]:
# Load iris data
from sklearn.datasets import load_iris

iris = load_iris()
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [27]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [28]:
# Create features and target
X = iris.data
y = iris.target
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [29]:
# Create VarianceThreshold object with a variance with a 0.5 threhold
thresholder = VarianceThreshold(threshold=.5)

# Conduct variance threhold
X_high_variance = thresholder.fit_transform(X)

In [30]:
# View first five rows with featuers with variances above threshold
X_high_variance[0:5]

array([[5.1, 1.4, 0.2],
       [4.9, 1.4, 0.2],
       [4.7, 1.3, 0.2],
       [4.6, 1.5, 0.2],
       [5. , 1.4, 0.2]])

## Boston dataset (Encoders)

In [59]:
from sklearn.datasets import load_boston

boston = load_boston()
X = boston.data
y = boston.target

In [60]:
from sklearn.model_selection import train_test_split

X_train, y_train, X_test, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [61]:
import numpy as np
Y = np.random.choice(('Male', 'Female'), size = (10))
Y

array(['Female', 'Male', 'Female', 'Male', 'Female', 'Female', 'Male',
       'Female', 'Male', 'Female'], dtype='<U6')

In [62]:
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
yt = le.fit_transform(Y)
print(yt)

[0 1 0 1 0 0 1 0 1 0]


## One-hot Encoder (Car Consumer dataset)

In [177]:
import pandas as pd
import numpy as np
dataset = pd.read_csv("Data.csv")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [178]:
# Taking care of missing values
from sklearn.preprocessing import Imputer 
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [183]:
# Encodign categorical data and Independant variables
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_X = LabelEncoder()

# Encode labels in column 'species'
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()

# Encoding the Dependant Variables
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)
print(X)
print(y)

[[0.00000000e+00 1.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00 4.40000000e+01 7.20000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 1.00000000e+00 2.70000000e+01 4.80000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  1.00000000e+00 0.00000000e+00 3.00000000e+01 5.40000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 1.00000000e+00 3.80000000e+01 6.10000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  1.00000000e+00 0.00000000e+00 4.00000000e+01 6.37777778e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00 3.50000000e+01 5.80000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 1.00000000e+00 3.87777778e+01 5.20000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 0.00000000e+00 4.80000000e+01 7.90000000e+04]


/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


# Vectorizer

In [39]:
# Vectorizers

sample = ['problem of evil problem evil queen horizon problem']

In [19]:
# Count vectorizer check the frequency of word appearing in data
from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer()
x = vec.fit_transform(sample)

In [20]:
import pandas as pd
pd.DataFrame(x.toarray(), columns=vec.get_feature_names())

evil  horizon  of  problem  queen
0     2        1   1        3      1

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
vec = TfidfVectorizer()  # Inverse Document frequency
X = vec.fit_transform(sample)
pd.DataFrame(X.toarray(), columns=vec.get_feature_names())

## For every word weightage is mentioned

evil  horizon    of  problem  queen
0   0.5     0.25  0.25     0.75   0.25

In [ ]:
# Feature Engineering 
# To handle Dictionary kind of data
data = [
    {"price": 850000, 'rooms': 4, 'neighbor'}
]

vec = DictVectorizer(sparse=True, dtype = int)
d = vec.fit_transofrm(data)
print(d)

DictVectorizer - need / CountVectorizer / TfidVectorizer

## Derived Features 
Deriving features from exisiting features

In [22]:
import numpy as np
import matplotlib.pyplot as plt
x = np.array([1, 2, 3, 4, 5])
y = np.array([4, 2, 1, 3, 7])
#plt.scatter(x, y);

In [23]:
from sklearn.linear_model import LinearRegression
X = x[:, np.newaxis]
model = LinearRegression().fit(X, y)
yfit = model.predict(X)
plt.scatter(x, y)  # Plot the points
plt.plot(x, yfit)  # Plot the line
plt.xlabel('Temperature')
plt.ylabel('Solar Energy')

Text(0, 0.5, 'Solar Energy')

In [24]:
# Need a more sophisticated model to describe the relationship
# Polynomial Feature can be used when we have very less no. of 
# features, helps generate new features
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=3, include_bias = False)
X2 = poly.fit_transform(X)
print(X2)

[[  1.   1.   1.]
 [  2.   4.   8.]
 [  3.   9.  27.]
 [  4.  16.  64.]
 [  5.  25. 125.]]


In [25]:
# Multiple Linear Regression
model = LinearRegression().fit(X2, y)
yfit = model.predict(X2)
plt.scatter(x, y)
plt.plot(x, yfit)
plt.xlabel('Temperature')
plt.ylabel('Solar Energy')

Text(0, 0.5, 'Solar Energy')

In [31]:
# Pipeline
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import Imputer 
from numpy import nan
import numpy as np

X = np.array([[nan, 0, 3], 
             [3, 7, 9], 
             [3, 5, 2], 
             [4, nan, 6], 
             [8, 8, 1]])
y = np.array([14, 16, -1, 8, -5])

model = make_pipeline(Imputer(strategy = 'mean'), 
                             PolynomialFeatures(degree=5), LinearRegression()
                             )


/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [32]:
model.fit(X, y)  # X with missing values, from above
print(y)

[14 16 -1  8 -5]


In [33]:
X.shape

(5, 3)

In [ ]:
missing value
pandas function
numpy function
imputer class (mean mode)
normalization - l1, l2 normalization
variance threshold
encoders 
one-hot encoder 
vectorizer - dict, vect, 
polynomial feature - checking linear REgression
pipeline
pca 

## PCA

In [73]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy import cov
from numpy.linalg import eig

A = array([[1, 2], [3, 4], [5, 6]])

In [74]:
M = mean(A.T, axis = 1)
print(M)

[3. 4.]


In [75]:
C = A - M

In [76]:
print(C)

[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]


In [77]:
# calculate covariance matrix of centered matrix 
V = cov(C.T)
print(V)
# eigenecomposition of covariance matrix

[[4. 4.]
 [4. 4.]]


In [78]:
values, vectors = eig(V)
print(values)

[8. 0.]


In [79]:
# project data 
P = vectors.T.dot(C.T)
print(P.T)

[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]


In [80]:
from sklearn.datasets import fetch_mldata

In [81]:
# PCA

from sklearn import datasets
digits = datasets.load_digits()

In [82]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [83]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [84]:
from sklearn.model_selection import train_test_split # test_size: what proportion of original data is used for test set

train_img, test_img, train_lbl, test_lbl = train_test_split(digits.data, digits.target, test_size = 0.25, random_state = 0)

In [85]:
train_img.shape

(1347, 64)

In [86]:
from sklearn.decomposition import PCA # Make an instance of the Model 
pca = PCA(.95)  # It will be having 95% information will be there
# 5% info will be lost

In [87]:
pca.fit(train_img)  # Train

PCA(copy=True, iterated_power='auto', n_components=0.95, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [88]:
# After PCA analysis we get 28 columns from 64 columns
pca.n_components_  

28

In [89]:
train_img.shape

(1347, 64)

In [90]:
train_img = pca.transform(train_img)
test_img = pca.transform(test_img) # test model

In [91]:
train_img.shape

(1347, 28)

In [92]:
# Demo of Label Encoder 
import numpy as np
Y = np.random.choice(('Male', 'Female'), size=(10))
Y

array(['Male', 'Female', 'Female', 'Female', 'Male', 'Male', 'Male',
       'Female', 'Female', 'Female'], dtype='<U6')