In [31]:
import numpy as np
import pandas as pd
import sklearn 
from sklearn.neighbors import KNeighborsClassifier

dataset = pd.read_csv("knn.csv")

x = dataset.iloc[:, :-1].values  # Features
y = dataset.iloc[:, 2].values  # Target

In [32]:
classifier = KNeighborsClassifier(n_neighbors = 3)
classifier.fit(x, y)  # training

X_test = np.array([4, 2])

y_predict = classifier.predict(x)
print(y_predict)

from sklearn.metrics import confusion_matrix

confusion_matrix(y, y_predict)
# clf.score(X_test, y_test)

['N' 'N' 'N' 'P' 'P' 'N']


array([[2, 2],
       [2, 0]])

In [33]:
# Assinning features and label variables 
# First Feature 
weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy', 'Rainy', 'Overcast', 'Sunny', 'Sunny', 
          'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']
# Second Feature 
temp = ['Hot', 'Hot', 'Hot', 'Mild', 'Cool', 'Cool', 'Cool', 'Mild', 'Cool', 'Mild', 'Mild', 'Mild', 'Hot', 'Mild']

# Label or target variable 
play = ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No']

In [34]:
# Import LabelEncoder 
from sklearn import preprocessing 
# Creating Label Encoder 
le = preprocessing.LabelEncoder()
#Converting whether string labels into numbers
weather_encoded = le.fit_transform(weather)
print(weather_encoded)
# converting temp strign labels into numbers 
temp_encoded = le.fit_transform(temp)
# converting play string labels into numbers 
label = le.fit_transform(play)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [35]:
# Combining weather and temp into single listof tuples 
features = list(zip(weather_encoded, temp_encoded))

In [46]:
from sklearn.neighbors import KNeighborsRegressor
model = KNeighborsClassifier(n_neighbors = 3)
model.fit(features, label)
predicted = model.predict([[0, 2]])
print(predicted)

[1]


## For Regression

In [36]:
### for regression
import numpy as np
import pandas as pd
import sklearn
from sklearn.neighbors import KNeighborsRegressor
dataset = pd.read_csv('knn1.csv')
x = dataset.iloc[:, :-1].values
print(x)
y = dataset.iloc[:, 2].values
print(y)

[[ 5.   45.  ]
 [ 5.11 26.  ]
 [ 5.6  30.  ]
 [ 5.9  34.  ]
 [ 4.8  40.  ]
 [ 5.8  36.  ]
 [ 5.3  19.  ]
 [ 5.8  28.  ]
 [ 5.5  23.  ]
 [ 5.6  32.  ]]
[77 47 55 59 72 60 40 60 45 58]


In [37]:
classifier = KNeighborsRegressor(n_neighbors = 5) # k = 5
classifier.fit(x, y) # training
x_test = np.array([5.50, 26])
y_predict = classifier.predict([x_test])  # Testing 
print(y_predict)

[53.]
