In [36]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy import cov
from numpy.linalg import eig

A = array([[1, 2], [3, 4], [5, 6]])

In [37]:
M = mean(A.T, axis = 1)
print(M)

[3. 4.]


In [38]:
C = A - M

In [39]:
print(C)

[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]


In [40]:
# calculate covariance matrix of centered matrix 
V = cov(C.T)
print(V)
# eigenecomposition of covariance matrix

[[4. 4.]
 [4. 4.]]


In [41]:
values, vectors = eig(V)
print(values)

[8. 0.]


In [42]:
# project data 
P = vectors.T.dot(C.T)
print(P.T)

[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]


In [43]:
from sklearn.datasets import fetch_mldata

In [44]:
# PCA

from sklearn import datasets
digits = datasets.load_digits()

In [45]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [46]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [47]:
from sklearn.model_selection import train_test_split # test_size: what proportion of original data is used for test set

train_img, test_img, train_lbl, test_lbl = train_test_split(digits.data, digits.target, test_size = 0.25, random_state = 0)

In [48]:
train_img.shape

(1347, 64)

In [49]:
from sklearn.decomposition import PCA # Make an instance of the Model 
pca = PCA(.95)  # It will be having 95% information will be there
# 5% info will be lost

In [51]:
pca.fit(train_img)  # Train

PCA(copy=True, iterated_power='auto', n_components=0.95, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [52]:
# After PCA analysis we get 28 columns from 64 columns
pca.n_components_  

28

In [53]:
train_img.shape

(1347, 64)

In [54]:
train_img = pca.transform(train_img)
test_img = pca.transform(test_img) # test model

In [56]:
train_img.shape

(1347, 28)

In [57]:
# Demo of Label Encoder 
import numpy as np
Y = np.random.choice(('Male', 'Female'), size=(10))
Y

array(['Male', 'Female', 'Female', 'Female', 'Female', 'Female', 'Female',
       'Female', 'Female', 'Male'], dtype='<U6')